export { default as bannerIMG } from './banner.jpg'
export { default as landingOneIMG } from './landing-one.jpg'
export { default as landingTwoIMG } from './landing-two.jpg'
export { default as landingThreeIMG } from './landing-three.jpg'
export { default as landingFoorIMG } from './landing-foor.jpg'
